# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with thseed (or created alongside the db with dbEx  cities = City.create([{ name: 'Chicago' }, { namegen' }])
#   te(name: 'Emanuel', city: citie   "canon" name="Canon" />


    brands =  ["apple",
    "nikon",
    "sony",
    "samsung",
    "panasonic",
    "fujifilm",
    "htc",
    "pentax",
    "kodak",
    "casio",
    "leica",
    "sonyericsson",
    "blackberry",
    "minolta",
    "motorola",
    "gopro",
    "ricoh",
    "hp",
    "sigma",
    "phaseone",
    "sanyo",
    "benq",
    "kddi",
    "lg",
    "toshiba",
    "nintendo",
    "epson",
    "kyocera",
    "docomo",
    "polaroid",
    "vivitar",
    "palm",
    "google",
    "sharp",
    "acer",
    "jvc",
    "concord",
    "leaf",
    "helio"]
